export const RESET_PASSWORD_FEATURE_SELECTOR_KEY = 'resetPassword';

export const REQUEST_OTP = `[${RESET_PASSWORD_FEATURE_SELECTOR_KEY}] Request OTP`;
export const REQUEST_OTP_SUCCESS = `[${RESET_PASSWORD_FEATURE_SELECTOR_KEY}] Request OTP Success`;
export const REQUEST_OTP_FAILURE = `[${RESET_PASSWORD_FEATURE_SELECTOR_KEY}] Request OTP Failure`;

export const RESET_PASSWORD = `[${RESET_PASSWORD_FEATURE_SELECTOR_KEY}] Reset Password`;
export const RESET_PASSWORD_SUCCESS = `[${RESET_PASSWORD_FEATURE_SELECTOR_KEY}] Reset Password Success`;
export const RESET_PASSWORD_FAILURE = `[${RESET_PASSWORD_FEATURE_SELECTOR_KEY}] Reset Password Failure`;

