export const ATTENDANCE_DETAIL_FEATURE_SELECTOR_KEY = 'attendanceDetail';

export const LOAD_ATTENDANCE_DETAIL = `[${ATTENDANCE_DETAIL_FEATURE_SELECTOR_KEY}] Load Attendance Detail`;
export const LOAD_ATTENDANCE_DETAIL_SUCCESS = `[${ATTENDANCE_DETAIL_FEATURE_SELECTOR_KEY}] Load Attendance Detail SUCCESS`;
export const LOAD_ATTENDANCE_DETAIL_FAILURE = `[${ATTENDANCE_DETAIL_FEATURE_SELECTOR_KEY}] Load Attendance Detail FAILURE`;

export const CLEAR_ATTENDANCE_DETAIL = `[${ATTENDANCE_DETAIL_FEATURE_SELECTOR_KEY}] Clear Attendance Detail`;
