export const CHECK_IN_FEATURE_SELECTOR_KEY = 'checkInCheckOut';

export const CHECK_IN_REQUEST = `[${CHECK_IN_FEATURE_SELECTOR_KEY}] Request`;

export const CHECK_IN_SUCCESS = `[${CHECK_IN_FEATURE_SELECTOR_KEY}] Success`;

export const CHECK_IN_FAILURE = `[${CHECK_IN_FEATURE_SELECTOR_KEY}] Failure`;

export const CHECK_OUT_REQUEST = `[${CHECK_IN_FEATURE_SELECTOR_KEY}] Request`;

export const CHECK_OUT_SUCCESS = `[${CHECK_IN_FEATURE_SELECTOR_KEY}] Success`;

export const CHECK_OUT_FAILURE = `[${CHECK_IN_FEATURE_SELECTOR_KEY}] Failure`;
